version: '2'
services:

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      - DOCKER_LABELS=true
    ports:
      - "27017:27017"
    expose:
      - 27017

  rabbitmq:
    image: rabbitmq:3.6.6-management
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    logging:
      driver: none

  scheduler-service:
    image: sammlerio/scheduler-service
    container_name: scheduler-service
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - LOAD_JOBS_FROM_FILE=true
#      - SAMMLER_JOBS_SERVICE_URI=http://jobs-service:3003
    command: ["npm", "run", "start:watch"]
    volumes:
      - ./node_modules/scheduler-service:/home
      - ./configs/scheduler-service/jobs:/opt/scheduler-service/src/config/jobs

  strategy-twitter:
    build:
      context: .
    container_name: strategy-twitter
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=3000
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=SAMMLER_STRATEGY_TWITTER--DEV
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - TWITTER_CONSUMER_KEY=$S5R_STRATEGY_TWITTER__CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET=$S5R_STRATEGY_TWITTER__CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN=$S5R_STRATEGY_TWITTER__ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET=$S5R_STRATEGY_TWITTER__ACCESS_TOKEN_SECRET
    volumes:
      - "./src:/opt/strategy-twitter/src"
    command: ["npm", "run", "start:watch"]
