jobs:
  - name: job-twitter.cmd.sync-user
    enabled: true
    strategy: interval
    exchange:
      type: topic
      name: twitter
    key: twitter.cmd.sync.user
    payload:
      screen_name: waltherstefan
      s5r_user_id: 1
    interval: 20000
    options:
      correlationId: "{{correlation_id}}"
